/*
 Project: MySafeFob  ui_nav.cpp
  Copyright (c) 2026 Luc Lebosse. All rights reserved.

  This code is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.

  This code is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/
/**
 * @file ui_nav.cpp
 * @brief MySafeFob App — interactive menu + Settings screens.
 *
 * Pattern lifted verbatim from references/test_apps/freeinkui-poc/main/
 * main.cpp (POC, fully proven on hardware): Frame/InteractionBuffer route()
 * mutates focus AFTER the draw that used it, so every input cycle draws
 * twice — once (thrown away on screen) to register hit-rects and resolve
 * the input, once more with the now-current focus/active state, and only
 * that second draw is flushed to the panel. Multi-screen navigation (this
 * file's first — see docs/UI-SPECS.md) keeps that same discipline: only
 * WHAT gets drawn changes per screen, not the render loop's shape.
 *
 * Also owns the ADR-012 activity manager: idle timeout tracked across
 * this loop's own button/touch events plus board_activity_notify() calls
 * from main.c (Power button presses, REPL commands = "serial activity").
 */
#include "ui_nav.h"
#include "settings_store.h"

extern "C" {
#include "eink.h"
#include "hw_config.h"
#include "buttons.h"
#include "touch.h"
#include "battery.h"
#include "power_mgr.h"
#include "esp_log.h"
#include "esp_timer.h"
#include "esp_system.h"
#include "esp_app_desc.h"
#include "esp_cpu.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"
}

#include <atomic>
#include <cstdio>
#include <cstring>

#include <FreeInkUIDisplayTarget.h>
#include <FreeInkUIIcon.h>
#include "battery_icons_gen.h"
#include "SmallFont.h"

using namespace freeink::ui;

/* WORKAROUND (2026-09-18): see touch.c's twin comment -- standard
 * ESP_LOG* calls from this file never reach the serial monitor (100%
 * reproducible), while a raw printf() from the exact same call site
 * always works. Scoped to this translation unit only; revert once the
 * real cause is found. */
#undef ESP_LOGE
#undef ESP_LOGW
#undef ESP_LOGI
#define ESP_LOGE(tag, fmt, ...) do { \
        printf("E (%lld) %s: " fmt "\r\n", (long long)(esp_timer_get_time() / 1000), tag, ##__VA_ARGS__); \
        fflush(stdout); \
    } while (0)
#define ESP_LOGW(tag, fmt, ...) do { \
        printf("W (%lld) %s: " fmt "\r\n", (long long)(esp_timer_get_time() / 1000), tag, ##__VA_ARGS__); \
        fflush(stdout); \
    } while (0)
#define ESP_LOGI(tag, fmt, ...) do { \
        printf("I (%lld) %s: " fmt "\r\n", (long long)(esp_timer_get_time() / 1000), tag, ##__VA_ARGS__); \
        fflush(stdout); \
    } while (0)

static const char *TAG = "ui_nav";
static uint8_t s_fb[SCREEN_FB_SIZE];

/* Interaction budget: fixed-zone Settings button + Back + the busiest
 * screen (SETTINGS: 7 rows, 2 of them currently enabled/hit-tested) fits
 * well under 16; widened from the original placeholder's <8> for headroom
 * as more screens/rows come online (docs/UI-SPECS.md). */
static constexpr size_t kMaxInteractions = 16;
using AppFrame = Frame<kMaxInteractions>;

/* All 8 font slots default to the same bundled kNotoSansFont (~24px);
 * this slot is registered with a smaller rasterization (SmallFont.h,
 * generated by gen_font.py at 16px) for compact chrome labels like the
 * footer's version/timestamp line. Slot 0 (default) is left untouched —
 * only text that explicitly opts into this slot shrinks. */
static constexpr FontId kSmallFontSlot = 1;

/* Implemented in splash.cpp (boots/redraws the sleep screen before
 * power_mgr_shutdown() — same trampoline as a manual long Power press,
 * main.c's power_button_task). */
extern "C" void board_sleep_screen_show(void);

/* -----------------------------------------------------------------------
 * Screens (docs/UI-SPECS.md §1.4). Only the subset actually built this
 * pass: HOME (placeholder), SETTINGS + its Controls/About sub-screens,
 * and a simplified touch diagnostic (raw coordinate readout — the full
 * guided 3x3 grid from UI-SPECS §2.12 is deferred).
 * ----------------------------------------------------------------------- */
enum class Screen { Home, Settings, SettingsControls, SettingsAbout, TouchDiag };

static Screen s_screen = Screen::Home;
/* UI-SPECS.md §1.3.1: one remembered screen id, not a navigation stack —
 * set when the fixed-zone Settings button is tapped from HOME, consumed
 * by SETTINGS's own Back. Sub-screens under Settings Back to Settings
 * directly (see the ACTION_BACK dispatch below), never through this slot. */
static Screen s_settings_return_to = Screen::Home;

static InteractionBuffer<kMaxInteractions> s_interactions;

static const char *screen_name(Screen s)
{
    switch (s) {
    case Screen::Home:             return "Home";
    case Screen::Settings:         return "Settings";
    case Screen::SettingsControls: return "SettingsControls";
    case Screen::SettingsAbout:    return "SettingsAbout";
    case Screen::TouchDiag:        return "TouchDiag";
    }
    return "?";
}

/* UI-SPECS.md §1.1: "Full refresh only on: screen type change ... Everything
 * else uses fast DU refresh." Starts true so the very first draw of the
 * whole task is full too (no previous frame to diff against anyway — the
 * driver would force one either way, but this makes the app's own intent
 * explicit rather than leaning on that fallback). */
static bool s_force_full_refresh = true;

static void switch_screen(Screen s)
{
    ESP_LOGI(TAG, "screen: %s -> %s", screen_name(s_screen), screen_name(s));
    s_screen = s;
    s_force_full_refresh = true;
    /* Focus from the previous screen's widgets doesn't correspond to
     * anything on the new one — start with nothing focused rather than a
     * stale/out-of-range index. */
    s_interactions.setFocusedIndex(-1);
}

/* ADR-012: idle timeout (no button/touch/serial input) before auto-sleep.
 * Runtime value, not a compile-time constant — settings_store.h's
 * settings_store_get_idle_timeout_s() (0 = disabled, dev default per its
 * own doc comment; a shipped device should default to 45s). */
static std::atomic<int64_t> s_last_activity_us{0};

void board_activity_notify(void)
{
    s_last_activity_us.store(esp_timer_get_time(), std::memory_order_relaxed);
}

/* UI-SPECS.md §2.12/§3: a short Power press-and-release (main.c's
 * power_button_task, gated behind the "Power short press = Select"
 * setting) injects one confirm pulse here, equivalent to a touch-Home
 * tap. Power never joins this loop's own input reads — this is a single
 * pending flag consumed by the next iteration. */
static std::atomic<bool> s_power_confirm_pending{false};

void board_ui_nav_power_confirm(void)
{
    s_power_confirm_pending.store(true, std::memory_order_relaxed);
}

enum : ActionId {
    ACTION_SLEEP_NOW = 1,
    ACTION_OPEN_SETTINGS = 2,
    ACTION_BACK = 3,
    ACTION_OPEN_CONTROLS = 4,
    ACTION_OPEN_TOUCH_DIAG = 5,
    ACTION_OPEN_ABOUT = 6,
    ACTION_TOGGLE_POWER_CONFIRM = 7,
};

/* -----------------------------------------------------------------------
 * Input sampling task (2026-09-18, decoupling from the render/flush loop).
 *
 * board_ui_nav_task's draw+eink_display_fb()/_fast() cycle blocks the
 * whole task for the flush duration (~0.5-1s fast / ~2-4s full). Sampling
 * buttons/touch inline in that same loop (the original design) meant any
 * button or touch edge that started and ended entirely within a flush's
 * blocking window was never read at all — dropped silently, no trace.
 * Physical buttons mostly got away with it (button_wait_press's own
 * blocking-until-release wait means a still-held button is always caught
 * whenever the loop gets back to it), but a quick touch tap frequently
 * didn't survive.
 *
 * Fix: buttons + touch are now sampled continuously in this own task, at
 * their own pace, translated into discrete edge events, and handed to the
 * render task through a queue deep enough to buffer a burst of taps
 * across one flush. The render task drains it with a bounded wait
 * (doubles as its idle-timeout polling tick) instead of sampling hardware
 * directly. REPL/serial input is NOT folded in here — esp_console owns
 * its own task and blocking read loop (main.c) and was never coupled to
 * this one's flush in the first place; it already calls
 * board_activity_notify() directly from its own command handlers.
 * ----------------------------------------------------------------------- */
enum class InputEventType : uint8_t {
    ButtonLeft,
    ButtonRight,
    ButtonPowerActivity,   /* keep-alive only — Power is never acted on here */
    TouchPress,
    TouchRelease,
};

struct InputEvent {
    InputEventType type;
    int16_t x = 0;
    int16_t y = 0;
    bool home = false;
    int16_t raw_x = 0;   /* pre-calibration GT911 values -- carried through
                          * just for the touch diagnostic screen, never
                          * used for hit-testing (see touch.h/.c). */
    int16_t raw_y = 0;
};

static constexpr size_t kInputQueueLen = 16;
static QueueHandle_t s_input_queue = nullptr;
static bool s_touch_ok = false;

static void input_sampler_task(void *arg)
{
    (void)arg;
    /* Decisive diagnostic (2026-09-18): zero dependency on touch/eink --
     * if this doesn't show up either, the problem is upstream of
     * anything touch-specific (task never scheduled, or its serial
     * output specifically never reaching the terminal). Raw printf +
     * fflush alongside ESP_LOGE: disambiguates "task never runs" from
     * "something ESP_LOG-specific (tag level, vprintf hook) swallows it". */
    printf("\r\n### RAW PRINTF: input_sampler_task ENTER (core=%d) ###\r\n", (int)esp_cpu_get_core_id());
    fflush(stdout);
    ESP_LOGE(TAG, "=== input_sampler_task ENTER (core=%d) ===", (int)esp_cpu_get_core_id());

    /* Debug/diagnosis (2026-09-18): the very first reads right after
     * touch_init() (POR dance + possible 185-byte config upload) are
     * suspect until proven otherwise — untested theory is a stale/garbage
     * point or status bit right after init could fire a spurious tap.
     * Give the controller a short settle window before trusting any edge;
     * logged explicitly so this shows up in the serial monitor if it ever
     * fires, rather than silently masking a real bug. */
    const int64_t touch_settle_until_us = esp_timer_get_time() + 300000;   /* 300 ms */

    bool touch_was_pressed = false;
    int16_t touch_down_x = 0, touch_down_y = 0;
    int16_t touch_down_raw_x = 0, touch_down_raw_y = 0;
    bool touch_down_home = false;

    while (1) {
        /* Left/Right only — Power (BTN_3) stays exclusively owned by
         * power_mgr / power_button_task (main.c), never acted on here.
         * button_wait_press blocks until release when a button IS held,
         * which is fine in this dedicated task (it no longer stalls the
         * render/flush loop). */
        button_id_t btn = button_wait_press(20);
        if (btn == BTN_1) {
            /* 2026-09-18: capture-side timestamp, paired with a
             * processing-side one in apply_input_event() -- compares
             * button_wait_press()'s own debounce/release-wait latency
             * against however long the event then sits queued behind a
             * busy render/flush loop, to tell the two apart. */
            ESP_LOGI(TAG, "button LEFT captured");
            InputEvent ev{InputEventType::ButtonLeft};
            xQueueSend(s_input_queue, &ev, 0);
        } else if (btn == BTN_2) {
            ESP_LOGI(TAG, "button RIGHT captured");
            InputEvent ev{InputEventType::ButtonRight};
            xQueueSend(s_input_queue, &ev, 0);
        } else if (btn == BTN_3) {
            ESP_LOGI(TAG, "button POWER captured (activity only)");
            InputEvent ev{InputEventType::ButtonPowerActivity};
            xQueueSend(s_input_queue, &ev, 0);
        }

        if (s_touch_ok) {
            touch_point_t tp = touch_read();
            const bool press_edge = tp.pressed && !touch_was_pressed;
            const bool release_edge = !tp.pressed && touch_was_pressed;

            if (press_edge || release_edge) {
                ESP_LOGI(TAG, "touch %s: x=%d y=%d home=%d raw=(%d,%d)%s",
                         press_edge ? "press" : "release", tp.x, tp.y, (int)tp.home,
                         tp.raw_x, tp.raw_y,
                         esp_timer_get_time() < touch_settle_until_us ? " [settle-ignored]" : "");
            }

            if (esp_timer_get_time() >= touch_settle_until_us) {
                if (press_edge) {
                    touch_down_x = tp.x;
                    touch_down_y = tp.y;
                    touch_down_raw_x = tp.raw_x;
                    touch_down_raw_y = tp.raw_y;
                    touch_down_home = tp.home;
                    InputEvent ev{InputEventType::TouchPress, tp.x, tp.y, tp.home, tp.raw_x, tp.raw_y};
                    xQueueSend(s_input_queue, &ev, 0);
                }
                if (release_edge) {
                    InputEvent ev{InputEventType::TouchRelease, touch_down_x, touch_down_y,
                                  touch_down_home, touch_down_raw_x, touch_down_raw_y};
                    xQueueSend(s_input_queue, &ev, 0);
                }
            }
            touch_was_pressed = tp.pressed;
        }
    }
}

/* TESTING ONLY (2026-09-18) — deep sleep drops the USB-serial-JTAG
 * connection, which was making it impossible to tell whether a touch
 * test actually triggered Sleep or something else: the log line proving
 * it either never got flushed before the disconnect, or the terminal
 * missed it across the reconnect. Set to 0 to restore real sleep once
 * touch behavior is understood — do not ship with this at 1. */
#define MSF_DEBUG_NO_SLEEP 1

static void enter_sleep_from_idle_or_menu(const char *reason)
{
#if MSF_DEBUG_NO_SLEEP
    ESP_LOGW(TAG, "sleep button activated (%s) -- MSF_DEBUG_NO_SLEEP=1, staying awake", reason);
    return;
#else
    if (!power_mgr_claim_terminal_action()) {
        /* Another path (Power long-press, REPL `sleep`) already won the
         * race — nothing to do, it's handling the transition. */
        return;
    }
    ESP_LOGI(TAG, "entering sleep (%s)", reason);
    board_sleep_screen_show();
    power_mgr_shutdown();   /* never returns on success */
#endif
}

/* Primary action slot's Y (2026-09-18): shared between draw_fixed_zone()'s
 * Settings button (Home) and draw_back_and_title()'s "< Back" button
 * (everywhere else) -- same physical position regardless of which one
 * occupies it. */
static constexpr int16_t kHeaderActionY = 76;

/* -----------------------------------------------------------------------
 * Fixed zone (UI-SPECS.md §1.3): battery icon/%, a divider line, and
 * "Settings" -- a button on Home (reachable both by direct tap and by
 * Left/Right), or a plain label once already inside the Settings
 * hierarchy. No date/time yet -- time_svc/RTC isn't wired into the UI
 * layer, that slot stays reserved per §1.3 until it is.
 * ----------------------------------------------------------------------- */
static int16_t draw_fixed_zone(DisplayTarget &target, AppFrame &frame, int16_t screen_width)
{
    /* Battery % + status icon (ADR-014, CW2017 already validated at the
     * driver level). Icon (2026-09-18): Lucide battery-{charging,full,
     * medium,low,warning}, generated by tools/gen_icons.py into
     * battery_icons_gen.h — see docs/esp-project-boilerplate/ for why
     * Lucide (freeink-sdk's icon set) rather than LVGL's default Font
     * Awesome. Charging takes priority over the SoC-based icon; no
     * dedicated "critical" icon in Lucide's set, battery-warning fills
     * that role. Not cached: one I2C read per redraw is cheap enough at
     * this refresh rate (button presses/taps, not a fast loop). */
    uint8_t soc = 0;
    bool charging = false;
    bool have_battery = battery_read(&soc, &charging);

    /* Icon doubled 2026-09-18 (user request: the header has enough
     * thickness to afford it) -- 24px -> 48px. The text next to it
     * (below) stays the default font/size, matching the rest of the
     * screen -- only the icon scales up. */
    const freeink::Icon *battery_icon = &icon_battery_48;
    if (have_battery) {
        if (charging) {
            battery_icon = &icon_battery_charging_48;
        } else if (soc >= 80) {
            battery_icon = &icon_battery_full_48;
        } else if (soc >= 50) {
            battery_icon = &icon_battery_medium_48;
        } else if (soc >= 20) {
            battery_icon = &icon_battery_low_48;
        } else {
            battery_icon = &icon_battery_warning_48;
        }
    }

    const int16_t icon_x = static_cast<int16_t>(screen_width - 48 - 12);
    const int16_t icon_y = 8;
    target.bitmap(Rect{icon_x, icon_y, 48, 48}, bitmapFromIcon(*battery_icon), BitmapMode::Contain);

    char battery_text[8];
    if (have_battery) {
        snprintf(battery_text, sizeof(battery_text), "%u%%", (unsigned)soc);
    } else {
        snprintf(battery_text, sizeof(battery_text), "--");
    }
    TextStyle battery_style;
    /* Default font (slot 0, kNotoSansFont ~24px) -- 2026-09-18, user
     * request: match the rest of the screen's text instead of a
     * dedicated MediumFont sized to the icon. Only the icon stays
     * doubled (24px -> 48px); the text no longer scales with it. */
    battery_style.align = TextAlign::Right;
    /* DisplayTarget::text() places multi-glyph runs at baseline =
     * rect.y + font.ascent, not a vertical center of rect.height. The
     * formula-derived rect.y (icon_y+7, from kNotoSansFont's metrics)
     * still sat a few px low in practice (2026-09-18 hardware check) --
     * nudged up empirically rather than re-deriving the formula, same
     * as every other font-alignment fix in this function. */
    target.text(Rect{static_cast<int16_t>(icon_x - 158), static_cast<int16_t>(icon_y + 2), 150, 48},
                battery_text, battery_style);

    target.line(Point{0, 64}, Point{screen_width, 64}, 1, Paint::solid(Color::Black));

    /* Primary action slot, Rect{24,76,130,36} -- always the same spot,
     * whatever occupies it: a "Settings" button on Home (the only way
     * to enter the Settings hierarchy), or (2026-09-18) the "< Back"
     * button drawn by draw_back_and_title() on every screen under it --
     * back replaces the button that would otherwise sit there, same
     * slot, so the primary action stays in one consistent place across
     * screens instead of jumping around. Nothing drawn here directly
     * for non-Home screens; draw_back_and_title() (called by each
     * sub-screen right after this function returns) fills it.
     *
     * Positioned below the header line (2026-09-18): the earlier fix
     * (Rect{10,10,...} -> Rect{24,20,...}) reduced but never eliminated
     * a direct-tap miss right at the top of the panel -- a hardware
     * test (4-corner+center, docs/touch-calibration-notes.md) showed
     * the touch sensor's active area only starts around raw_y~21 (just
     * below where this row used to sit). Moving the only *interactive*
     * element in the header below the divider line puts it solidly
     * inside the confirmed-active area instead of right at its fragile
     * top edge. */
    if (s_screen == Screen::Home) {
        ButtonProps settings_btn;
        settings_btn.label = "Settings";
        settings_btn.action = ACTION_OPEN_SETTINGS;
        button(frame, Rect{24, kHeaderActionY, 130, 36}, settings_btn);
    } else {
        /* Non-interactive now that it's not a button (2026-09-18, user
         * request) -- moved up into the header proper, alongside the
         * icon/battery row, instead of squatting in the action slot
         * that "< Back" now needs. */
        TextStyle settings_label;
        settings_label.bold = true;
        target.text(Rect{24, 16, 200, 40}, "Settings", settings_label);
    }

    return 124;   /* Y offset where each screen's contextual content starts. */
}

/* Footer — mirror of draw_fixed_zone()'s header: one horizontal line,
 * one line of small text below it, fixed at the bottom of every screen.
 * Firmware version + build date/time, both already embedded by the IDF
 * build (esp_app_desc_t) with zero extra bookkeeping on our side: no
 * PROJECT_VER is set (root CMakeLists.txt), so `version` falls back to
 * `git describe --always --dirty` (e.g. "86200cd-dirty"); `date`/`time`
 * are this binary's compile timestamp, not the device's clock (there is
 * no RTC-backed wall clock wired up yet, ADR-... time_svc). */
static void draw_footer(DisplayTarget &target, const Rect &screen)
{
    const int16_t line_y = static_cast<int16_t>(screen.height - 40);
    target.line(Point{0, line_y}, Point{screen.width, line_y}, 1, Paint::solid(Color::Black));

    const esp_app_desc_t *app_desc = esp_app_get_description();
    char buf[96];
    snprintf(buf, sizeof(buf), "%s  %s %s", app_desc->version, app_desc->date, app_desc->time);

    TextStyle footer_style;
    footer_style.font = kSmallFontSlot;
    footer_style.align = TextAlign::Center;
    target.text(Rect{0, static_cast<int16_t>(line_y + 8), screen.width, 24}, buf, footer_style);
}

static void draw_back_and_title(DisplayTarget &target, AppFrame &frame, const Rect &screen,
                                const char *title)
{
    /* Fixed at the same slot draw_fixed_zone() uses for the Settings
     * button on Home (2026-09-18, user request): "< Back" replaces it,
     * same place, rather than sitting lower at the old per-screen
     * content offset -- one consistent primary-action position across
     * every screen instead of it jumping around depending on which
     * screen you're on. */
    ButtonProps back;
    back.label = "< Back";
    back.action = ACTION_BACK;
    button(frame, Rect{24, kHeaderActionY, 130, 36}, back);

    /* title == nullptr skips the centered title entirely (2026-09-18):
     * the top-level Settings screen used to pass "Settings" here, right
     * below a header that -- once it started showing "Settings" as a
     * label for every screen under it, not just a button on Home -- made
     * the exact same word appear three times on screen at once. Kept
     * for sub-screens (Controls & Calibration, About, Touch diagnostic),
     * whose titles are NOT redundant with the header's generic
     * "Settings" label. */
    if (title != nullptr) {
        TextStyle title_style;
        title_style.align = TextAlign::Center;
        title_style.bold = true;
        target.text(Rect{0, kHeaderActionY, screen.width, 36}, title, title_style);
    }
}

/* -----------------------------------------------------------------------
 * HOME (placeholder — "About" moved to SETTINGS_ABOUT, "Sleep now" stays).
 * ----------------------------------------------------------------------- */
static void draw_home(DisplayTarget &target, AppFrame &frame, const Rect &screen, int16_t y)
{
    TextStyle title;
    title.align = TextAlign::Center;
    title.bold = true;
    target.text(Rect{0, static_cast<int16_t>(y + 30), screen.width, 40}, "MySafeFob", title);

    ButtonProps sleep_now;
    sleep_now.label = "Sleep now";
    sleep_now.action = ACTION_SLEEP_NOW;
    button(frame, Rect{40, 300, static_cast<int16_t>(screen.width - 80), 70}, sleep_now);

    TextStyle footer;
    footer.align = TextAlign::Center;
    target.text(Rect{0, 490, screen.width, 24}, "Left/Right = focus", footer);
    target.text(Rect{0, 520, screen.width, 24}, "Touch Home = confirm", footer);
}

/* -----------------------------------------------------------------------
 * SETTINGS (menu, UI-SPECS.md §2.11). Only "Controls & Calibration" and
 * "About" are enabled this pass — the rest need components that don't
 * exist yet (secret_store/PIN, frontlight UI binding, time_svc, SD backup)
 * and are rendered disabled so the menu's shape doesn't need to change
 * later, only each row's enabled flag.
 * ----------------------------------------------------------------------- */
struct SettingsMenuItem {
    const char *label;
    const char *subtitle;
    bool enabled;
    ActionId action;
};

static const SettingsMenuItem kSettingsMenu[] = {
    {"Controls & Calibration", nullptr, true, ACTION_OPEN_CONTROLS},
    {"Security", "PIN, auto-lock - not available yet", false, NO_ACTION},
    {"Display", "Frontlight - not available yet", false, NO_ACTION},
    {"Time & Sync", "Not available yet", false, NO_ACTION},
    {"Backup (SD)", "Not available yet", false, NO_ACTION},
    {"Owner info", "Sleep screen - not available yet", false, NO_ACTION},
    {"About", nullptr, true, ACTION_OPEN_ABOUT},
};

static void draw_settings(DisplayTarget &target, AppFrame &frame, const Rect &screen, int16_t y)
{
    draw_back_and_title(target, frame, screen, nullptr);   /* header already says "Settings" */

    int16_t row_y = static_cast<int16_t>(y + 48);
    const int16_t row_h = 60;
    const int16_t row_gap = 6;
    for (const SettingsMenuItem &item : kSettingsMenu) {
        SettingRowProps row;
        row.label = item.label;
        row.subtitle = item.subtitle;
        row.action = item.action;
        row.enabled = item.enabled;
        row.drawChevron = item.enabled;
        settingRow(frame, Rect{20, row_y, static_cast<int16_t>(screen.width - 40), row_h}, row);
        row_y = static_cast<int16_t>(row_y + row_h + row_gap);
    }
}

/* -----------------------------------------------------------------------
 * SETTINGS_CONTROLS (UI-SPECS.md §2.12) — the two settings this pass
 * actually delivers: the Power-short-press toggle and the link to the
 * touch diagnostic screen.
 * ----------------------------------------------------------------------- */
static void draw_settings_controls(DisplayTarget &target, AppFrame &frame, const Rect &screen, int16_t y)
{
    draw_back_and_title(target, frame, screen, "Controls");

    int16_t row_y = static_cast<int16_t>(y + 56);

    ToggleRowProps toggle_row;
    toggle_row.row.label = "Power short press";
    toggle_row.row.subtitle = "= Select (confirm)";
    toggle_row.checked = settings_store_get_power_short_confirm();
    toggle_row.toggleAction = ACTION_TOGGLE_POWER_CONFIRM;
    toggleRow(frame, Rect{20, row_y, static_cast<int16_t>(screen.width - 40), 64}, toggle_row);
    row_y = static_cast<int16_t>(row_y + 64 + 10);

    SettingRowProps diag_row;
    diag_row.label = "Touch diagnostic";
    diag_row.subtitle = "Live raw coordinates";
    diag_row.action = ACTION_OPEN_TOUCH_DIAG;
    diag_row.drawChevron = true;
    settingRow(frame, Rect{20, row_y, static_cast<int16_t>(screen.width - 40), 60}, diag_row);
}

/* -----------------------------------------------------------------------
 * SETTINGS_ABOUT (UI-SPECS.md §2.20) — on-screen equivalent of the REPL
 * `about` command (F-20, main.c's cmd_about).
 * ----------------------------------------------------------------------- */
static void draw_settings_about(DisplayTarget &target, AppFrame &frame, const Rect &screen, int16_t y)
{
    draw_back_and_title(target, frame, screen, "About");

    TextStyle body;
    char idf_line[48];
    snprintf(idf_line, sizeof(idf_line), "IDF: %s", esp_get_idf_version());

    int16_t line_y = static_cast<int16_t>(y + 60);
    target.text(Rect{20, line_y, static_cast<int16_t>(screen.width - 40), 28}, "MySafeFob (MSF)", body);
    line_y = static_cast<int16_t>(line_y + 34);
    target.text(Rect{20, line_y, static_cast<int16_t>(screen.width - 40), 28}, "Board: x4pro", body);
    line_y = static_cast<int16_t>(line_y + 34);
    target.text(Rect{20, line_y, static_cast<int16_t>(screen.width - 40), 28}, idf_line, body);
}

/* -----------------------------------------------------------------------
 * Touch diagnostic (simplified from UI-SPECS.md §2.12's full 3x3 guided
 * grid — this pass ships the "minimum useful" version the spec itself
 * calls out: a live raw-coordinate readout, updated from the same touch
 * sample the main loop already reads every cycle. No fix/reprogram
 * attempt here (docs/touch-calibration-notes.md) — diagnosis only.
 * ----------------------------------------------------------------------- */
static touch_point_t s_last_touch = { false, false, -1, -1, 0, 0 };

/* Small "+" marker so a calibration tap has an unambiguous, precise
 * target instead of "somewhere near this corner" -- the ambiguity that
 * slowed down every earlier round of this calibration effort (verbally
 * matching a tap to a log line after the fact). */
static void draw_crosshair(DisplayTarget &target, int16_t x, int16_t y)
{
    constexpr int16_t kArm = 10;
    target.line(Point{static_cast<int16_t>(x - kArm), y}, Point{static_cast<int16_t>(x + kArm), y},
                1, Paint::solid(Color::Black));
    target.line(Point{x, static_cast<int16_t>(y - kArm)}, Point{x, static_cast<int16_t>(y + kArm)},
                1, Paint::solid(Color::Black));
}

static void draw_touch_diag(DisplayTarget &target, AppFrame &frame, const Rect &screen, int16_t y)
{
    draw_back_and_title(target, frame, screen, "Touch diagnostic");

    TextStyle body;
    body.align = TextAlign::Center;
    char buf1[48];
    char buf2[48];
    if (s_last_touch.x >= 0) {
        /* Both stages shown (2026-09-18, calibration is still unresolved,
         * docs/touch-calibration-notes.md): "logical" is what actually
         * gets hit-tested against widget Rects ((EINK_H-1)-raw_x on X,
         * touch_rescale_y() on Y); "raw" is the untouched GT911 register
         * value. Showing both side by side removes the "which stage did
         * this logged number come from" ambiguity that slowed down the
         * last few calibration rounds. */
        snprintf(buf1, sizeof(buf1), "logical: x=%d y=%d%s", s_last_touch.x, s_last_touch.y,
                 s_last_touch.home ? "  (home)" : "");
        snprintf(buf2, sizeof(buf2), "raw: x=%d y=%d", s_last_touch.raw_x, s_last_touch.raw_y);
    } else {
        snprintf(buf1, sizeof(buf1), "tap the screen");
        buf2[0] = '\0';
    }
    target.text(Rect{0, static_cast<int16_t>(y + 20), screen.width, 32}, buf1, body);
    target.text(Rect{0, static_cast<int16_t>(y + 56), screen.width, 32}, buf2, body);

    /* Five explicit targets (2026-09-18): tap each one at a time, exactly
     * on the crosshair's center, and read the two lines above after each
     * tap -- removes the need to describe "roughly which corner" in
     * words. Placed well clear of the header (button at y=76-112) and
     * footer (line at screen.height-40) so they don't visually clash with
     * either. */
    const int16_t left = 20;
    const int16_t right = static_cast<int16_t>(screen.width - 20);
    const int16_t cx = static_cast<int16_t>(screen.width / 2);
    const int16_t top = 240;
    const int16_t mid = 440;
    const int16_t bottom = 640;
    draw_crosshair(target, left, top);
    draw_crosshair(target, right, top);
    draw_crosshair(target, cx, mid);
    draw_crosshair(target, left, bottom);
    draw_crosshair(target, right, bottom);
}

/* -----------------------------------------------------------------------
 * Dispatch
 * ----------------------------------------------------------------------- */
static void draw_current_screen(DisplayTarget &target, AppFrame &frame)
{
    memset(s_fb, 0xFF, sizeof(s_fb));
    const Rect screen = frame.screen();
    int16_t content_y = draw_fixed_zone(target, frame, screen.width);

    switch (s_screen) {
    case Screen::Home:             draw_home(target, frame, screen, content_y); break;
    case Screen::Settings:         draw_settings(target, frame, screen, content_y); break;
    case Screen::SettingsControls: draw_settings_controls(target, frame, screen, content_y); break;
    case Screen::SettingsAbout:    draw_settings_about(target, frame, screen, content_y); break;
    case Screen::TouchDiag:        draw_touch_diag(target, frame, screen, content_y); break;
    }

    draw_footer(target, screen);
}

static void handle_action(ActionId action)
{
    ESP_LOGI(TAG, "action: %d (screen=%s)", (int)action, screen_name(s_screen));
    switch (action) {
    case ACTION_SLEEP_NOW:
        enter_sleep_from_idle_or_menu("Sleep now menu item");
        break;
    case ACTION_OPEN_SETTINGS:
        if (s_screen == Screen::Home) {
            s_settings_return_to = Screen::Home;
        }
        switch_screen(Screen::Settings);
        break;
    case ACTION_BACK:
        switch (s_screen) {
        case Screen::Settings:         switch_screen(s_settings_return_to); break;
        case Screen::SettingsControls: switch_screen(Screen::Settings); break;
        case Screen::SettingsAbout:    switch_screen(Screen::Settings); break;
        case Screen::TouchDiag:        switch_screen(Screen::SettingsControls); break;
        default: break;
        }
        break;
    case ACTION_OPEN_CONTROLS:
        switch_screen(Screen::SettingsControls);
        break;
    case ACTION_OPEN_ABOUT:
        switch_screen(Screen::SettingsAbout);
        break;
    case ACTION_OPEN_TOUCH_DIAG:
        switch_screen(Screen::TouchDiag);
        break;
    case ACTION_TOGGLE_POWER_CONFIRM:
        settings_store_set_power_short_confirm(!settings_store_get_power_short_confirm());
        break;
    default:
        break;
    }
}

/* Translates one queued InputEvent into the InputSnapshot fields
 * Frame/InteractionBuffer expect. Factored out so the coalescing loop in
 * board_ui_nav_task can apply it to more than just the first event of a
 * burst. */
static void apply_input_event(const InputEvent &inev, InputSnapshot &input)
{
    switch (inev.type) {
    case InputEventType::ButtonLeft:
        ESP_LOGI(TAG, "button LEFT processed (dequeued)");
        input.focusPrev = true;
        break;
    case InputEventType::ButtonRight:
        ESP_LOGI(TAG, "button RIGHT processed (dequeued)");
        input.focusNext = true;
        break;
    case InputEventType::ButtonPowerActivity:
        break;   /* keep-alive only */
    case InputEventType::TouchPress:
        s_last_touch = {true, inev.home, inev.x, inev.y, inev.raw_x, inev.raw_y};
        input.touchPressed = true;
        input.touchX = inev.x;
        input.touchY = inev.y;
        if (inev.home) input.confirm = true;
        break;
    case InputEventType::TouchRelease:
        input.touchReleased = true;
        input.touchX = inev.x;
        input.touchY = inev.y;
        break;
    }
}

void board_ui_nav_task(void *arg)
{
    (void)arg;

    /* Decisive diagnostic (2026-09-18): see input_sampler_task's twin
     * comment -- logged before touching buttons/touch/eink at all. */
    printf("\r\n### RAW PRINTF: board_ui_nav_task ENTER (core=%d) ###\r\n", (int)esp_cpu_get_core_id());
    fflush(stdout);
    ESP_LOGE(TAG, "=== board_ui_nav_task ENTER (core=%d) ===", (int)esp_cpu_get_core_id());

    buttons_init();
    s_touch_ok = touch_init();
    ESP_LOGI(TAG, "touch: %s", s_touch_ok ? "OK" : "ABSENT");

    s_input_queue = xQueueCreate(kInputQueueLen, sizeof(InputEvent));
    xTaskCreate(input_sampler_task, "ui_input", 4096, NULL, 4, NULL);

    s_last_activity_us.store(esp_timer_get_time(), std::memory_order_relaxed);

    DisplayTarget target(s_fb, EINK_W, EINK_H, EINK_WB, Orientation::Portrait);
    target.setFont(kSmallFontSlot, kNotoSansSmallFont);
    const DeviceContext device = target.deviceContext();

    while (1) {
        InputSnapshot input{};
        bool activity = false;

        /* Bounded wait (also this loop's idle-timeout polling tick) —
         * hardware sampling itself happens in input_sampler_task, never
         * blocked by this task's own eink flush below. */
        InputEvent inev{};
        if (xQueueReceive(s_input_queue, &inev, pdMS_TO_TICKS(50)) == pdTRUE) {
            activity = true;
            apply_input_event(inev, input);

            /* Coalesce a burst of already-queued events (2026-09-18): drain
             * and resolve (but never flush) every event but the last, so N
             * queued button/touch events collapse into a single redraw +
             * flush instead of N sequential ones -- the e-ink flush is the
             * real bottleneck (0.5-4s), not input handling, so 3 quick
             * Right presses no longer mean 3 back-to-back panel updates.
             * Each throwaway resolve still runs draw_current_screen() and
             * handle_action() for real (advancing focus/screen state
             * correctly, mid-burst screen switches included) -- it just
             * never reaches eink_display_fb*(). Capped so a runaway queue
             * can't stall this loop indefinitely. */
            constexpr int kMaxCoalesce = 8;
            for (int i = 0; i < kMaxCoalesce; ++i) {
                InputEvent next{};
                if (xQueueReceive(s_input_queue, &next, 0) != pdTRUE) break;

                AppFrame throwaway(target, device, input, s_interactions);
                draw_current_screen(target, throwaway);
                ActionEvent throwaway_ev = throwaway.finish();
                if (throwaway_ev) handle_action(throwaway_ev.action);

                input = InputSnapshot{};
                apply_input_event(next, input);
            }
        }

        if (s_power_confirm_pending.exchange(false, std::memory_order_relaxed)) {
            activity = true;
            input.confirm = true;
        }

        if (activity) {
            board_activity_notify();
        }

        const bool changed = s_force_full_refresh || input.focusPrev || input.focusNext ||
                             input.confirm || input.touchPressed || input.touchReleased;
        if (!changed) {
            uint32_t idle_timeout_s = settings_store_get_idle_timeout_s();
            if (idle_timeout_s > 0) {
                int64_t idle_ms = (esp_timer_get_time() - s_last_activity_us.load(std::memory_order_relaxed)) / 1000;
                if (idle_ms >= (int64_t)idle_timeout_s * 1000) {
                    enter_sleep_from_idle_or_menu("idle timeout, no button/touch/serial input");
                    /* Only reaches here if another caller already claimed the
                     * transition — avoid re-triggering every 50ms while that
                     * transition is in flight. */
                    vTaskDelay(pdMS_TO_TICKS(1000));
                }
            }
            continue;
        }

        /* Pass 1 (thrown away on screen, just to register hit-rects):
         * resolves the current input -> updates focused_/active_. */
        AppFrame frame(target, device, input, s_interactions);
        draw_current_screen(target, frame);
        ActionEvent ev = frame.finish();

        if (ev) {
            handle_action(ev.action);
        }

        /* Pass 2: real draw with the now-current focus/active state (and
         * whatever screen handle_action() may have just switched to) — the
         * one that actually gets flushed, eliminating the one-frame lag. */
        AppFrame frame2(target, device, InputSnapshot{}, s_interactions);
        draw_current_screen(target, frame2);

        if (s_force_full_refresh) {
            eink_display_fb(s_fb);
            s_force_full_refresh = false;
        } else {
            eink_display_fb_fast(s_fb);
        }
    }
}
