/**
 * @file font8x16.h
 * @brief 8x16 bitmap font (ASCII 0x20-0x7E)
 *        Auto-generated by generate_font.py - do not edit
 */

#pragma once

#include <stdint.h>

#define FONT_WIDTH  8
#define FONT_HEIGHT 16
#define FONT_BYTES_PER_ROW 1

/**
 * @brief Get glyph data for a character
 * @param c ASCII character (0x20-0x7E)
 * @return Pointer to 16 bytes of glyph data
 */
const uint8_t *font8x16_get_glyph(char c);
