/* 
 Project: MySafeFob  font8x16.h
  Copyright (c) 2026 Luc Lebosse. All rights reserved.

  This code is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.

  This code is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/
/**
 * @file font8x16.h
 * @brief 8x16 bitmap font (ASCII 0x20-0x7E)
 *        Auto-generated by generate_font.py - do not edit
 */

#pragma once

#include <stdint.h>

#define FONT_WIDTH  8
#define FONT_HEIGHT 16
#define FONT_BYTES_PER_ROW 1

/**
 * @brief Get glyph data for a character
 * @param c ASCII character (0x20-0x7E)
 * @return Pointer to 16 bytes of glyph data
 */
const uint8_t *font8x16_get_glyph(char c);
